id: I9E6B901F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T23:50:10+00:00'
last_modified: '2022-06-08T17:32:20.913819+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG03892
  title: སོག་པོའི་སྐད་ཡིག་གི་བརྡ་སྤྲོད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    260A:
      image_group_id: I00KG03967
      title: ''
      total_pages: 418
      order: 1
      base_file: 260A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
